name: C/C++ CI

on:
  push:
    branches: [ "master", "git-actions" ]
  pull_request:
    branches: [ "master", "git-actions" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test

